# application-test.yml
spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

  rabbitmq:
    listener:
      simple:
        auto-startup: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:8090/auth/realms/oauth2-realm}
          jwk-set-uri: ${JWT_JWK_SET_URI:http://localhost:8090/auth/realms/oauth2-realm/protocol/openid-connect/certs}

jwt:
  auth:
    converter:
      principle-attribute: ${JWT_PRINCIPAL_ATTR:preferred_username}
      resource-id: ${JWT_RESOURCE_ID:microservices_client}


eureka:
  client:
    enabled: false
server:
  port: 0